### ISSUE TITLE
pouchdb-utils@6.3.2 is lacking `uuid` dependency

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb#6613]
```
$ npm install pouchdb-utils
$ node -e 'require("pouchdb-utils")'
module.js:471
    throw err;
    ^

Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/npm-test/node_modules/pouchdb-utils/lib/index.js:14:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

It works in `pouchdb-utils@6.2.0`

**Comment by daleharvey** [comment]
As mentioned on irc, the fix is hopefully @ https://github.com/pouchdb/pouchdb/commit/28fba0870b1438626ca57f2278fc94d102c4c5fa, if you could test it would be happy to release

**Comment by gr2m** [comment]
on it

**Comment by gr2m** [comment]
confirmed locally that https://github.com/pouchdb/pouchdb/commit/28fba0870b1438626ca57f2278fc94d102c4c5fa fixes the problem.
