### ISSUE TITLE
Promises and node v0.12

### ISSUE THREAD

**Issue by mainakae** [pouchdb/pouchdb#3839]
Hello all,

I've noticed that after upgrading my node, form 0.10.x to 0.12.2, I'm no longer able to call the "finally" method on promises returned by the api; now it throws "TypeError: undefined is not a function".

var db = new PouchDB('http://localhost:5984/db");

db.allDocs().then(...).finally(...); // NO LONGER WORKING!

**Comment by daleharvey** [comment]
Hrm I dont think `Promise.finally` is in the official spec? if so it shouldnt have ever been part of our API apologies

**Comment by calvinmetcalf** [comment]
right and you were never able to do this in the browser, it's because we
only use bluebird for promises if native ones are not available

**Comment by daleharvey** [comment]
We should either 1. Figure out how to remove `finally` from bluebird promises, 2. Use a spec compliant lib, 3. Not support node versions that dont support native promises.

It looks like all stable releases of node support Promises natively but not sure what the uptake for these releases are, may be harsh to drop support already

**Comment by calvinmetcalf** [comment]
you can just switch to using lie only and not bluebird

**Comment by mainakae** [comment]
I know it's not part of the specification, I've been trying out lately lie, q and bluebird among others, and though it's somehow arguable and prone to change in the future, seems that bluebird is the right choice. In fact I adopted it as the promises library for my latest app (in part in sake of homogeneity with PouchDB).

The issue is not so much about loosing that functionality (again: as things go by, you might be inclined to chose another lib, and then following tightly the specification will be a bonus) but about some shaky things going on under the hood, maybe worth checking.

**Comment by daleharvey** [comment]
In node 0.12 Promises are natively supported, so it will start to use the native promises which dont have `.finally`, similiar to what happens in the browser. We have always planned to be spec compatible so we can remove any of our own Promises code when its widely enough supported. 

Removing bluebird and just using lie for older node versions sounds like a good plan

**Comment by nolanlawson** [comment]
I'm fine with removing bluebird and using `global.Promise || require('lie')`. Simplifies things a lot, although technically may justify a major version release.

**Comment by daleharvey** [comment]
Fixed in https://github.com/pouchdb/pouchdb/commit/09ce6c885dece08cc722d0897a546d694759eaee
