### ISSUE TITLE
Project doesn't build on Node 0.12 or io.js

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb#3572]
Seems to be a level down issue.

**Comment by zeroware** [comment]
I managed to build it without problem on node 0.12 two days ago...

**Comment by nolanlawson** [comment]
Ah okay, I see now. Apparently I can install PouchDB *as a user*, but if I do `npm install` inside the `pouchdb` project itself, I get the following error. Seems to be a problem with the `exec-sync` module.

```
> ffi@1.2.5 install /Users/nlawson/workspace-node/pouchdb/node_modules/exec-sync/node_modules/ffi
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/darwin64.o
  LIBTOOL-STATIC Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.cc:2:
../src/ffi.h:57:43: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> FFIPrepCif(const Arguments& args);
                                          ^~~~~~~~~
                                          v8::internal::Arguments
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:58:46: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> FFIPrepCifVar(const Arguments& args);
                                             ^~~~~~~~~
                                             v8::internal::Arguments
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:59:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> FFICall(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:60:45: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> FFICallAsync(const Arguments& args);
                                            ^~~~~~~~~
                                            v8::internal::Arguments
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:64:40: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Strtoul(const Arguments& args);
                                       ^~~~~~~~~
                                       v8::internal::Arguments
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/ffi.cc:2:
../src/ffi.h:94:41: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
    static Handle<Value> Callback(const Arguments& args);
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:133:7: note:
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/ffi.cc:19:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:878:13: note: declared protected
      here
  V8_INLINE HandleScope() {}
            ^
../src/ffi.cc:21:3: error: unexpected namespace name 'Buffer': expected expression
  Buffer *buf = Buffer::New(ptr, length, wrap_pointer_cb, user_data);
  ^
../src/ffi.cc:21:11: error: use of undeclared identifier 'buf'
  Buffer *buf = Buffer::New(ptr, length, wrap_pointer_cb, user_data);
          ^
../src/ffi.cc:22:16: error: no member named 'Close' in 'v8::HandleScope'
  return scope.Close(buf->handle_);
         ~~~~~ ^
../src/ffi.cc:22:22: error: use of undeclared identifier 'buf'
  return scope.Close(buf->handle_);
                     ^
../src/ffi.cc:28:33: error: too few arguments to function call, single argument
      'isolate' was not specified
  Local<Object> o = Object::New();
                    ~~~~~~~~~~~ ^
/Users/nlawson/.node-gyp/1.3.0/deps/v8/include/v8.h:2691:3: note: 'New' declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/ffi.cc:31:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlopen"),  WrapPointer((char *)dlopen));
         ~~~~~~~~^
../src/ffi.cc:32:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlclose"), WrapPointer((char *)dlclose));
         ~~~~~~~~^
../src/ffi.cc:33:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlsym"),   WrapPointer((char *)dlsym));
         ~~~~~~~~^
../src/ffi.cc:34:18: error: no member named 'NewSymbol' in 'v8::String'
  o->Set(String::NewSymbol("dlerror"), WrapPointer((char *)dlerror));
         ~~~~~~~~^
../src/ffi.cc:36:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("StaticFunctions"), o);
              ~~~~~~~~^
../src/ffi.cc:49:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "ffi_prep_cif", FFIPrepCif);
  ^~~~~~~~~~~~~~~
/Users/nlawson/.node-gyp/1.3.0/src/node.h:218:25: note: expanded from macro
      'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/nlawson/.node-gyp/1.3.0/src/node.h:206:13: note: candidate function [with
      TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback'
      (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../src/ffi.cc:50:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "ffi_prep_cif_var", FFIPrepCifVar);
  ^~~~~~~~~~~~~~~
/Users/nlawson/.node-gyp/1.3.0/src/node.h:218:25: note: expanded from macro
      'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/nlawson/.node-gyp/1.3.0/src/node.h:206:13: note: candidate function [with
      TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback'
      (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nlawson/workspace-node/pouchdb/node_modules/exec-sync/node_modules/ffi
gyp ERR! node -v v1.3.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v1.3.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nlawson/workspace-node/pouchdb/npm-debug.log
```

I tried it on two different MacBooks, each one running Yosemite, and I see the following error when I try to `npm install` on pouchdb

    Darwin cerulean.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

**Comment by tathata** [comment]
Seeing the same exception on my MacBook Pro (Retina, 15-inch, Late 2013), also running Yosemite and node version 0.12, but installing pouchdb v3.3.2-prerelease.

**Comment by daleharvey** [comment]
This is now fixed, testing iojs and 0.12 in travis
