### ISSUE TITLE
pouchdb-find, $or and multiple $regex conditions and nested properties

### ISSUE THREAD

**Issue by mrzslr** [pouchdb/pouchdb#8534]
### Issue
using `pouchdb-find` with the selector of `$or` array and multiple `$regex` conditions throws an error in the console. it seems that `$and` and multiple `$regex` works fine since this [commit](https://github.com/pouchdb/pouchdb/commit/0e27e23f4437bce134d0780a543f08a3020fa4de) has been merged.

### Info
- Environment: browser/hybrid app
- Platform: Chrome/iOS/Android
- Adapter: indexeddb
- Server: no server, PouchDB client.

### Reproduce

1. data downloaded and saved in PouchDB.
2. database index created with fields: `from.name` and `type`.
3. by running the code below, the error console which is attached will appear in the console. using `$and` works tho.

```js
db.find({
    selector: {
        {
            $or: [
                {"from.name": {$regex: /foo/i}},
                {type: {$regex: /bar/i}},
            ]
        }
    }
});
```

![image](https://user-images.githubusercontent.com/5070181/180789256-2e9d94c6-5bde-47a2-943f-13a417f8ff95.png)

**Comment by pete-hotchkiss** [comment]
This will be related to #8491 foe which there is a fix in PR - but it's awaiting approval. 

Theres been no updates since April though - not sure whats needed to get it resolved.

**Comment by corlissc** [comment]
+1. Also adding a textual representation of the error for those searching for the error message.

```
TypeError: userValue.every is not a function. (In 'userValue.every(function (regexValue) {
        return regexMatch(docFieldValue, regexValue);
      })', 'userValue.every' is undefined)
```

**Comment by mrzslr** [comment]
one thing that I didn't consider was: `$regex` command cannot be run on an indexed field. I think it wasn't mentioned in docs tho.

**Comment by Przecza** [comment]
Hi, I have similiar issue with this query: 

```js
db.find({
  use_index: 'fooBarIndex',
  selector: {
    objectType: { $eq: 'foo' },
    bar: { $elemMatch: { $regex: /text/i) } },
  },
  limit: 5,
})
```
The root source seems to be the `Pouch-selector-core\lib\utils.js` - `massageSelector` functionis ignoring nested $regex. The PR for #8491  seems to be addressing this. 

Downgrading `pouchdb-selector-core` to 7.1.1. made it work aggain.

**Comment by gwen1230** [comment]
Same issue

**Comment by gwen1230** [comment]
When this fix will be available ?

**Comment by rgraddy** [comment]
Same issue. Works fine in 7.2.2

**Comment by pete-hotchkiss** [comment]
I believe yesterday's fix will sort this (7.3.1) there had been a solution merged for this a while back but only just had a release

https://pouchdb.com/2022/11/11/pouchdb-7.3.1.html

**Comment by eduardoMendozaO2** [comment]
Buenos días,
En la versión 7.3.1 sigo teniendo el mismo problema.Si bajo la versión de pouchdb a la 7.2.2 funciona bien.Alguna idea para que funcione con la nueva publicación?

Hello, In version 7.3.1 I still have the same problem. If I downgrade pouchdb to 7.2.2 it works fine. Any ideas to make it work with the 7.3.1 version?

`$or: [
                        { fullDescription: { $regex: descriptionRegex } },
                        {
                            $and: [
                                { internalCode: { $exists: true } },
                                { ixpCode: { $exists: true } },
                                { description: { $regex: descriptionRegex } }
                            ]
                        }
                    ]`

`"pouchdb": "7.3.1",
    "pouchdb-all-dbs": "1.1.1",
    "pouchdb-find": "7.3.1",
    "pouchdb-upsert": "2.2.0",`

**Comment by eduardoMendozaO2** [comment]
Actualizo el mensaje anterior:

Update the previous message:

Work:
`
    "pouchdb": "7.3.1",
    "pouchdb-find": "7.2.2",
`
Not work:
`
    "pouchdb": "7.3.1",
    "pouchdb-find": "7.3.1",
`

pouchdb-find is the problem.
