### ISSUE TITLE
6.3.2 Error: Invalid Adapter: https

### ISSUE THREAD

**Issue by jefbarn** [pouchdb/pouchdb#6603]
### Issue
After updating to pouchdb 6.3.2, upon initializing the PouchDB instance, it throws an 'Error: Invalid Adapter: https' error.

### Info
Browser (Chrome 59)
Webpack
Custom build

### Reproduce
Write the steps for others to reproduce issue here. Providing a code example, links to a repository or a live example (JSBin etc) are even more helpful.
```
import PouchDB from 'pouchdb-core'
import * as PouchHttp from 'pouchdb-adapter-http'
import * as PouchAuth from 'pouchdb-authentication'
import * as PouchFind from 'pouchdb-find'

PouchDB.plugin(PouchHttp)
PouchDB.plugin(PouchAuth)
PouchDB.plugin(PouchFind)

PouchDB(url, {
      skip_setup: true,
      ajax: {
        timeout: 30000
      }
    })
```

Worked in 6.2.0

**Comment by daleharvey** [comment]
6.3.2 was a broken release, apologies, hopefully 6.3.4 should be fixed

**Comment by jefbarn** [comment]
Just tried again on 6.3.4, same error.

Did something change with the ES module packaging? Wondering if I need to tweak my webpack settings.

**Comment by daleharvey** [comment]
Nothing should have, we introduced 1 new dependency and that seems to have a large knock on effect, does import PouchDB from 'pouchdb' work?

**Comment by jefbarn** [comment]
I installed the 'pouchdb' npm module and switched to `import PouchDB from 'pouchdb'`
now I get
```
core.es5.js:1020 ERROR Error: Uncaught (in promise): ReferenceError: _global is not defined
ReferenceError: _global is not defined
    at zone.js:1476
    at attachBrowserEvents (index-browser.es.js:497)
    at new Changes (index-browser.es.js:512)
    at Object.<anonymous> (index-browser.es.js:4794)
    at Object.936 (index-browser.es.js:12183)
    at __webpack_require__ (bootstrap aba318c…:49)
```

**Comment by riddla** [comment]
@jefbarn, @daleharvey: This error stems from a corrupt zonejs release, see https://github.com/angular/zone.js/issues/835. Locking zonejs to `"zone.js": "0.8.12"` solves the `_global is not defined` error.

**Comment by jefbarn** [comment]
@riddla Thanks for the heads up on the zone.js issue.  It did fix the `_global is not defined`. Unfortunately, I'm still having problems with the latest pouchdb build using plugins.
Using pouchdb-browser now, and trying to attach pouchdb-find plugin,
`core.es5.js:1020 ERROR Error: Uncaught (in promise): TypeError: this.find is not a function` 
(I extend the Pouchdb object, hence 'this.find')

Looks like I'm still stuck on pouchdb 6.2.0 for now.

**Comment by riddla** [comment]
(Sorrx, I olny got a phone at the moment and I am rephrasing)

Using TypeScript/ES6 I had to change my imports also. From ...

import * as PouchDB from 'pouchdb-browser'
import * as PouchFind from 'pouchdb-find'

...to ...

import PouchDB from 'pouchdb-browser'
import PouchFind from 'pouchdb-find'

let db = new PouchDB();
db.plugin(PouchFind);

This is more or less pseudocode, I cam check my repo tomorrow if it does not help.

**Comment by jefbarn** [comment]
@riddla Awesome, that was the trick!
This is working now:
```
import PouchDB from 'pouchdb-core'
import PouchHttp from 'pouchdb-adapter-http'
import PouchAuth from 'pouchdb-authentication'
import PouchFind from 'pouchdb-find'

PouchDB.plugin(PouchHttp)
PouchDB.plugin(PouchAuth)
PouchDB.plugin(PouchFind)

...
```

**Comment by jefbarn** [comment]
Closing, have solution by slightly modifying the ES6 import syntax. (see above)
