### ISSUE TITLE
db.createIndex is not a function - pouchdb-find Ionic 3

### ISSUE THREAD

**Issue by Don-G** [pouchdb/pouchdb#6630]
Been on this for a day now, finally given up and open an issue.
I am working with Ionic 3.5, Angular 4, Pouchdb 6.3.4, Pouchdb-find 6.3.4
Pouchdb works fine.
I have installed both pouchdb and pouchdb-find via npm

**steps to reproduce**
**npm**
ionic start testapp
npm install pouchdb
npm install pouchdb-find
ionic serve -l

**here is a brief of my component using a blank ionic 3 template**

//start
`import { Component } from '@angular/core';`
`import { NavController } from 'ionic-angular';`
`import { Http } from '@angular/http';`
`import 'rxjs/add/operator/map';`
`import PouchDB from 'pouchdb';`
`declare var require: any;`
`PouchDB.plugin(require('pouchdb-find'));`
`@Component({`
`           selector: 'page-home',`
 `          templateUrl: 'home.html'`
`})`
`export class HomePage {`
`      constructor(public navCtrl: NavController) {`
`              var db = new PouchDB('testapp');`
`             db.createIndex({`
`              index: {fields: ['type']}`
`       });`
`   }`
`}`

//end
when i run i get error

Uncaught (in promise): TypeError: db.createIndex is not a function TypeError: db.createIndex is not a function at new HomePage (http://localhost:8101/build/main.js:57:12) at createClass (http://localhost:8101/build/vendor.js:11251:26) at createDirectiveInstance (http://localhost:8101/build/vendor.js:11082:37) at createViewNodes (http://localhost:8101/build/vendor.js:12445:49) at createRootView (http://localhost:8101/build/vendor.js:12350:5) at callWithDebugContext (http://localhost:8101/build/vendor.js:13565:42) at Object.debugCreateRootView [as createRootView] (http://localhost:8101/build/vendor.js:13025:12) at ComponentFactory_.create (http://localhost:8101/build/vendor.js:10271:46) at ComponentFactoryBoundToModule.create (http://localhost:8101/build/vendor.js:3807:29) at NavControllerBase._viewInit

**Comment by mardie** [comment]
I had the same problem and manged to fix it. We are using several pouchdb modules in an ionic project so we had to apply the fix for all of them.
Pouchdb modules are being wrapped into an object with a **default** property (containing the actual module). 
We added aliases in the webpack config file to load the dist file instead.

_<webpack.config.js>_


> 
    ...
    alias: {
      "pouchdb": "pouchdb/dist/pouchdb",
     <more modules>
    }
    ...

By default, as a consumer, I want to use dist files and I don't want to transpile all libraries every single time I build my project and sort out all build problems for all of them. I'm not sure if this was the intended behavior.

> https://github.com/pouchdb/pouchdb/blob/60355d56f671a603368c64330300a64e79cf698b/package.json#L5

**Comment by Don-G** [comment]
Hi, thanks for the reply. am not sure: where is webpack.config.js located

The only one i see is at node_modules/@ionic/app-scripts/config/webpack.config.js

and dont know where to add there

tried adding under module.exports.resolve
no change.


i did try this 
PouchDB.plugin(require('pouchdb-find').default);
but cant work with the objects keep getting objects is not a function.

**Comment by Don-G** [comment]
Tried working with the objects but am not sure how to implement and keep getting errors like
Cannot read property 'map' of undefined
    at massageIndexDef (index-browser.es.js:400)
    at createIndex$1 (index-browser.es.js:561)
    at index-browser.es.js:107

when i do this:
PouchDB.plugin(require('pouchdb-find').default);
this.db.createIndex(this.db,{
      index: {fields: ['type']}
    }).then(function (result) {
      console.log(result);
    }).catch(function (err) {
      console.log(err);
    });


will it prevent it being loaded as an object when using the dist file (still dont know where to do that)

**Comment by gnujeremie** [comment]
Here's how I import PouchDB in Ionic 2 : 
```
import PouchDB from 'pouchdb';
import PouchdbFind from 'pouchdb-find';

@Injectable()
export class PouchService {
    constructor(private _zone: NgZone) {
        PouchDB.plugin(PouchdbFind);
    }

    init() {
        this.remoteDB = new PouchDB(remote_uri, {ajax: {headers: {Authorization: "Basic "+token}}});
    }
}

```

**Comment by Don-G** [comment]
thanks for taking time to send me that.
tried that. but with the same error.

i dont think i have put this in the right place
<webpack.config.js>

...
alias: {
  "pouchdb": "pouchdb/dist/pouchdb",
 <more modules>
}
...

i placed it here: node_modules/config/webpack.config.js

is that right?

**Comment by gnujeremie** [comment]
I didn't change anything in webpack.config.js.
I just installed pouchdb and then imported it in my service provider.

**Comment by Naxo** [comment]
t: [](https://stackoverflow.com/questions/41512923/how-to-extend-default-webpack-config-in-ionic-v2)

**Comment by Don-G** [comment]
@mardie thanks agin. but did not work for me. got same error. object is not a function.
please can you share more details about how you managed to get it to work. did you use ionic 3?
thanks

**Comment by ralph-fuechtenkort** [comment]
I actually have the same problem. Followed most of the stuff explained here but app does not compile js anymore with the alias in place.
Any help appreciated. Near to give up with pouchb which i like normally very much and try something else :(

**Comment by CAYdenberg** [comment]
I believe the documentation at https://pouchdb.com/guides/mango-queries.html should be updated. 

Instead of
```js
var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-find'));
```

it should be

```
import PouchDB from 'pouchdb'
import Find from 'pouchdb-find'

PouchDB.plugin(Find)
```
