### ISSUE TITLE
Cannot npm install on current master

### ISSUE THREAD

**Issue by alxndrsn** [pouchdb/pouchdb#7256]
### Issue
```
git checkout master
npm install
```
->
```
…
Building pouchdb-ajax...
build error
Error: Cannot find module '/Users/user/workspaces/medic/pouchdb/packages/node_modules/pouchdb-ajax/package.json'
…
```

This seems to have been introduced in e35f949d1948913e4bb6a7f226de8b1af1c5d5c5 (@daleharvey).

### Info
- Environment: npm 5.6.0, node 9.5.0
- Platform: iOS

### Reproduce
```
git checkout master
npm install
```

**Comment by alxndrsn** [comment]
Looks like my local repo was dirty.  `git clean -dfx` fixed.
