### ISSUE TITLE
Support nesting $or in selector properties for db.find

### ISSUE THREAD

**Issue by mattjennings** [pouchdb/pouchdb#6664]
### Issue
Using an $or selector nested in a property produces the following error (and same for $and)

> Error: unknown operator "$or" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all

This kind of query works with Mango in CouchDB 2.0 (at least, in Project Fauxton if I test it in their "Run a Mango Query" section it works)

### Info
- Server: CouchDB 2.0, pouchdb 6.3.4

### Reproduce
Go to http://nolanlawson.github.io/pouchdb-find/ and put in:

```javascript
db.find({
  selector: {
      _id: {
        $or: [
          {$eq: "dk"},
          {$eq: "link"}
        ]
      }
  },
  sort: ['_id']
});
```

**Comment by rasdaniil** [comment]
Same story with $and :(

**Comment by mattjennings** [comment]
The reproduction method returns this error now:

`match@https://unpkg.com/pouchdb@6.2.0/dist/pouchdb.find.js:3065:20
every@[native code]
every@[native code]
filter@[native code]
filterInMemoryFields@https://unpkg.com/pouchdb@6.2.0/dist/pouchdb.find.js:2988:21
https://unpkg.com/pouchdb@6.2.0/dist/pouchdb.find.js:5507:40
promiseReactionJob@[native code]`

**Comment by mjafarpour** [comment]
**Issue**
Is any way to use nested $and, $or operator?

> app.js:654 Error: unknown operator "0" - should be one of $eq, $lte, $lt, $gt, $gte, $exists, $ne, $in, $nin, $size, $mod, $regex, $elemMatch, $type, $allMatch or $all

**Info**

- server: Couchdb 2.2, pouchdb 7.1.1

**Reproduce**
`{ "$or": [
               {"$and": [
																	{"data.tags": { "$in": ["word1"] } }, 
																	{"data.tags": { "$in": ["word2"] } } 
														]},
														{"$and": [
																	{"data.tags": { "$in": ["word3"] } }, 
																	{"data.tags": { "$in": ["word4"] } } 
														]}														
													 ] 
											} `
