### ISSUE TITLE
Pouchdb6.2.0 migration + Pouchdb-find => pouchdbUtils.isRemote is not a function at PouchDB$5.<anonymous>

### ISSUE THREAD

**Issue by numerized** [pouchdb/pouchdb#6467]
### Issue
Was working perfectly with Pouchdb-find 0.10.5 until I've migrated to Pouchdb 6.2.0 + Pouchdb-find 6.2.0

Now, simply rolling back to pouchdb-find 0.10.5 and keep pouchdb 6.2.0 works.

Migrating to Pouchdb-find 6.2.0 is raising exception error : 

```
Error: Uncaught (in promise): TypeError: pouchdbUtils.isRemote is not a function
TypeError: pouchdbUtils.isRemote is not a function
    at PouchDB$5.<anonymous> (main.js:49657)
    at main.js:62508
    at new t (polyfills.js:3)
    at PouchDB$5.<anonymous> (main.js:62495)
    at PouchDB$5.find (main.js:93503)
    at main.js:46198
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (main.js:69613)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:69604)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at XMLHttpRequest.invoke (polyfills.js:3)
    at v (polyfills.js:3)
    at s (polyfills.js:3)
    at polyfills.js:3
    at main.js:46231
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (main.js:69613)
    at t.invoke (polyfills.js:3)
    at e.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:69604)
    at t.invokeTask (polyfills.js:3)
    at e.runTask (polyfills.js:3)
    at i (polyfills.js:3)
    at XMLHttpRequest.invoke (polyfills.js:3)
```

### Info
- Environment: Ionic3
- Platform: Chrome/FF/Safari
- Adapter: WebSQL Chrome / IndexedDB firefox
- Server: Cloudant + Envoy + Pouchdb-find

### Reproduce

```
import * as PouchDB from 'pouchdb';
import * as PouchDBFind from 'pouchdb-find';
PouchDB.plugin(PouchDBFind);
PouchDB.debug.enable('pouchdb:find')

[...]

init(userLoginDetails){
    return new Promise((resolve, reject) => {
      this.userLoginDetails = userLoginDetails;

      this.todoDb = new PouchDB(userLoginDetails.user_id+'_todo_db');
      //this.todoDb = new PouchDB(userLoginDetails.user_id+'_todos');
      console.log(userLoginDetails.userDBs.coach)
      this.remote = userLoginDetails.userDBs.coach;

      let options = {
        live: true,
        retry: true,
        filter: 'type/by_type',
        query_params: { "type": 'todo' }
      };

      this.todoDb.sync(this.remote, options)
      .then(()=>{
          resolve();
        })
        .catch((err)=>{
          reject(err);
        });
    })

  }

[...]

getTodos() {
    return new Promise((resolve, reject) => {
      this.todoDb.find({
        selector: {
          type: {
            $in: ['todo', 'meeting']
          }
        }
        }).then((result) => {

        this.data = [];
        result.docs.forEach(element => {
          if(element)
            this.data.push(element)
        });

        this.todoDb.changes({live: true, since: 'now', include_docs: true}).on('change', (change) => {
          this.data = this.sharedPouchService.handleChanges(this.data, change, 'reverse');
        });

        resolve(this.data);

      }).catch((error) => {
        reject(error);
      });

    });
  }
```

If you have any questions, please don't hesitate.

**Comment by daleharvey** [comment]
Hrm seems strange, pouchdb-utils is on npm 6.2.0 and has isRemote in it. Is this a build error on your side?

**Comment by numerized** [comment]
Thanks for reply, I rebuilt many times and remove my node_modules folders many times and npm install without any errors... When I rollback pouchdb-find to 0.10.5 and keep pouchdb 6.2.0, it works.

**Comment by numerized** [comment]
What can I do ?

**Comment by garrensmith** [comment]
Can you provide a small sample project so we can reproduce the issue

All misspelling thanks to my iPhone.
________________________________

**Comment by numerized** [comment]
I wish I could.
I'll have more time soon and I'll try to dig this yes!

I'll ping you

**Comment by numerized** [comment]
When I try to activate pouchdb on cordova through sqlite plugin I have same type of error:

```
TypeError: pouchdbUtils.assign is not a function. (In 'pouchdbUtils.assign({}, opts, {
        version: POUCH_VERSION,
        description: opts.name,
        size: size
    })', 'pouchdbUtils.assign' is undefined)
```

**Comment by numerized** [comment]
```
EXCEPTION: Uncaught (in promise): TypeError: pouchdbUtils.assign is not a function. (In 'pouchdbUtils.assign({}, opts, {
        version: POUCH_VERSION,
        description: opts.name,
        size: size
    })', 'pouchdbUtils.assign' is undefined)
WebSqlPouch@http://localhost:49152/www/build/main.js:232366:41
CordovaSQLitePouch@http://localhost:49152/www/build/main.js:174212:25
PouchDB$5@http://localhost:49152/www/build/main.js:35730:42
http://localhost:49152/www/build/main.js:27800:69
t@http://localhost:49152/www/build/polyfills.js:3:11970
init@http://localhost:49152/www/build/main.js:27798:27
http://localhost:49152/www/build/main.js:77761:35
onInvoke@http://localhost:49152/www/build/main.js:65115:43
run@http://localhost:49152/www/build/polyfills.js:3:7025
http://localhost:49152/www/build/polyfills.js:3:4664
invokeTask@http://localhost:49152/www/build/polyfills.js:3:10289
onInvokeTask@http://localhost:49152/www/build/main.js:65106:47
invokeTask@http://localhost:49152/www/build/polyfills.js:3:10232
runTask@http://localhost:49152/www/build/polyfills.js:3:7647
i@http://localhost:49152/www/build/polyfills.js:3:3714
invoke@http://localhost:49152/www/build/polyfills.js:3:11438
```

**Comment by numerized** [comment]
I have reinstalled all packages one by one and now it's working perfectly !
You can close this one.
