### ISSUE TITLE
TypeError: winningRev is not a function

### ISSUE THREAD

**Issue by lucapale** [pouchdb/pouchdb#7054]
### Issue
I am using PouchDB in a Ionic app.
With PouchDB 6.3.4 I was using the SQLite adapter for iOS. After upgrading to 6.4.2 i get this error and the db does not work:

Error in Success callbackId: SQLitePlugin1932871848 : TypeError: winningRev is not a function. (In 'winningRev(docInfo.metadata)', 'winningRev' is undefined)

### Info
- Environment: Ionic app
- Platform: iOS
- Adapter: pouchdb-adapter-cordova-sqlite with cordova-plugin-sqlite-2
- Server: Couchbase

### Reproduce
Use pouchdb-adapter-cordova-sqlite in iOS app with 6.4.2.

**Comment by yahyavi** [comment]
I started getting a similar error in desktop browsers (using rxdb 7.3.2 on top of pouchdb).
```
index.es.js:370 Uncaught TypeError: winningRev is not a function
    at insertDoc (index.es.js:370)
    at nextDoc (index.es.js:449)
    at index.es.js:452
    at Map.forEach (<anonymous>)
    at processDocs (index.es.js:426)
    at idbProcessDocs (index.es.js:330)
    at checkDone (index.es.js:354)
    at IDBRequest.readMetadata (index.es.js:364)
```

with the following additional errors:
```
Database has a global failure DOMException: Uncaught exception in event handler.
guardedConsole @ index-browser.es.js:486
idb.onabort @ index.es.js:1880
17:12:28.295 
```
```
CustomPouchError {status: 500, name: "indexed_db_went_bad", message: "unknown", error: true, reason: "AbortError", …}
```

**Comment by yahyavi** [comment]
There is a minimal repository available here:
https://github.com/yahyavi/simple_rxdb

Just do:
```
npm install
npm run build
```
open the localhost in the browser.

**Comment by lostnet** [comment]
I'm not sure of the cause, but:
The transpiled module node_modules/pouchdb-adapter-utils/lib/index.es.js has:
`import { isDeleted, merge, winningRev, revExists, isLocalId } from 'pouchdb-merge';`

despite the individual sources importing:
  `winningRev as calculateWinningRev
`
to prevent the local winningRev var from overshadowing the imported function. Changing var names in the module to prevent the shadowing seems to fix it..

**Comment by yahyavi** [comment]
Seems like this is a webpack+pouchdb issue. Downgrading to `pouchdb-adapter-idb: "6.4.1"` did the trick. (thanks to @pubkey [rxdb#499](https://github.com/pubkey/rxdb/issues/499)).
Hopefully Pouchdb can resolve this soon.

**Comment by daleharvey** [comment]
Seems like a super weird webpack bug, but happy if someone wants to send a PR that renames vars in a way to avoid this

**Comment by lostnet** [comment]
The pouchdb master's es module corrects the problem by renaming the var and moving rollup to 0.55.1 on branch 6999 also fixes it by renaming the var. So this looks like a bug in rollup fixed by:
[import name deshadowing fix](https://github.com/rollup/rollup/commit/0c3f4f990874bd9982413469228eefe3766f16fb)

**Comment by daleharvey** [comment]
Awesome thanks for confirming, manual rename would be fine too but we aren't going to be doing a release any time soon so probably best making sure you get the rollup fix

**Comment by yahyavi** [comment]
@lostnet @daleharvey 
I'm not sure I understand what the fix is until the next release (I am not using rollup). Should I update pouchdb's rollup version in its package.json to 0.55.1?
Right now I downgraded to `pouchdb-adapter-idb: "6.4.1"` to get it to work.

**Comment by pubkey** [comment]
As far as I understand this, a change in rollup would not fix this because it will not affect the `index.es.js` or `index.js` in pouchdb-adapter-idb which means the problem will still exist for webpack-users.

**Comment by lostnet** [comment]
@yahyavi The trouble is that 6.4.2 has a [0.55.0 rollup reference](https://github.com/pouchdb/pouchdb/blob/6999/package.json#L102) which causes it to generate invalid index.es.js in the case of adapter-utils.. You can go down to 6.4.1, rebuild the repo with a different rollup, or edit the index.es.js until there is a newer 6.4 version of pouchdb.

**Comment by daleharvey** [comment]
Sorry confused the issue, I thought it was the rollup version that users with building with not what built our transpiled version,seems like since a release is a while away I will probably need to do a patch release in the meantime (or auto +1 to anyone who has permission that wants to do one before I get the chance)

**Comment by yahyavi** [comment]
Thanks @pubkey @lostnet.
A patch release would be great @daleharvey.

**Comment by daleharvey** [comment]
Done the release @ https://github.com/pouchdb/pouchdb/releases/tag/6.4.3
