### ISSUE TITLE
export 'fetch' (imported as 'PouchDB') was not found in 'pouchdb' 

### ISSUE THREAD

**Issue by goltra** [pouchdb/pouchdb#8367]
I'm testing to send custom headers when creating a remote database with PouchDB. The fact is that according to the documentation the way to proceed is as follows (https://pouchdb.com/api.html). I'm working with pouchdb version 7.2.2:

var db = new PouchDB('http://example.com/dbname', {
  fetch: function (url, opts) {
    opts.headers.set('X-Some-Special-Header', 'foo');
    return PouchDB.fetch(url, opts);
  }
});
My code is almost copied and pasted

const db = new PouchDB(this.server, {
  fetch(url, opts) {
    opts.headers.set('xx-custom-xx', this.text);
    opts.credentials = 'include';
    return PouchDB.fetch(url, opts);
  }
});
When I try to launch it I get two errors:

Error1: "export 'fetch' (imported as 'PouchDB') was not found in 'pouchdb' (possible exports: default)" This error is being given by the line"return PouchDB.fetch(url, opts); "
Error2: "set does not exist on type headersinit"
I hope someone can help me. Thanks.

**Comment by dheimoz** [comment]
Hello @goltra , I am using cookie authentication for an app. First I have to post a request to the _session api, then I create the connection with

```js
const url = urlCouchdb + db;
options= {
      skip_setup: true,
    },
    fetch: (url, opts) => fetch(url, { ...opts, credentials: "include" })

remoteDB = new PouchDB(url, options);
```

So far, everything is working as expected.

**Comment by goltra** [comment]
> Hello @goltra , I am using cookie authentication for an app. First I have to post a request to the _session api, then I create the connection with
> 
> ```js
> const url = urlCouchdb + db;
> options= {
>       skip_setup: true,
>     },
>     fetch: (url, opts) => fetch(url, { ...opts, credentials: "include" })
> 
> remoteDB = new PouchDB(url, options);
> ```
> 
> So far, everything is working as expected.

**Comment by goltra** [comment]
@dheimoz Ok, I get it.. the problem are two.
- first, I was importing Pouch like this. "import * as PouchDB from 'pouchdb';"  I have notice in other project I import  with import PouchDB from 'pouchdb';
- In my new project with import PouchDB from 'pouchdb'; doesn't work because I don't have "allowSyntheticDefaultImports":true flag in tsconfig
Now my original code works. 

allowSyntheticDefaultImports flag is specified in doc but It does't work (no for me) with import * as PouchDB from 'pouchdb';

**Comment by dheimoz** [comment]
@goltra glad you figured out and shared your solution.
Cheers.
