### ISSUE TITLE
PouchDB 7.0.0 breaks cookie authentication

### ISSUE THREAD

**Issue by steodor** [pouchdb/pouchdb#7390]
### Issue
After upgrading to PouchDB 7.0.0 from 6.4.3, authentication using `pouchdb-authentication` stops working.

The call to the `_session` endpoint is successful (`{ ok: true, ... }`) but there's no `Set-Cookie` header on the response from the CouchDB server.

Even though the release notes say that we switched to `fetch`, the call to `_session` is being made via `XHR`. Could this mean it's a `pouchdb-authentication` issue?

### Info
- Environment: Browser
- Platform: Chrome, Firefox, iOS UIWebView, i assume any others
- Adapter: IndexedDB
- Server: CouchDB 2.1.1

**Comment by daleharvey** [comment]
Yup its pouchdb-authentication making the xhr call to _session, need to open the issue there cheers

**Comment by ptitjes** [comment]
@steodor We have an issue https://github.com/pouchdb-community/pouchdb-authentication/issues/239 and a PR https://github.com/pouchdb-community/pouchdb-authentication/pull/238.

But @daleharvey, our tests fail with this PR because I fail to correctly use a polyfill for `fetch`. Do you have examples of projects/libraries that correctly use `whatwg-fetch` in the context of  `PouchDB` ?

**Comment by daleharvey** [comment]
@ptitjes this is how pouchdb uses it https://github.com/pouchdb/pouchdb/blob/master/tests/integration/index.html#L10

**Comment by ptitjes** [comment]
@daleharvey I get errors like:
```
    'fetch' called on an object that does not implement interface Window.
    require<[206]</PouchDB.fetch
```
on Firefox (https://travis-ci.org/pouchdb-community/pouchdb-authentication/jobs/395600336#L4459)

and
```
    TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
        at Function.PouchDB.fetch
```
on Chrome (https://travis-ci.org/pouchdb-community/pouchdb-authentication/jobs/395600335#L4456).

But I correctly import the polyfill in my test scripts:
```
require('whatwg-fetch');
require('promise-polyfill');
```
(For instance in https://github.com/pouchdb-community/pouchdb-authentication/pull/238/commits/d0bf0be1109bfc96cbb6398c7a5f5874602f1e05#diff-7c069653dd18e564b675c7cfbcdfe691R3).

**Comment by steodor** [comment]
@daleharvey actually your [pull request](https://github.com/pouchdb/pouchdb/pull/7395) fixes the issue, the underlying problem was that pre-7 versions of PouchDB would send cookies with every request by default, whereas 7.0.0 doesn't any more. Until your PR is rolled out we applied the change after bundling (via our build script) and it works perfectly. Thanks!

**Comment by zeevl** [comment]
After way too much time struggling with this in an electron app, I finally discovered you can also get this to work by providing the `auth` option with credentials: 

```
    const remoteDb = new PouchDB(url, {
      skip_setup: true,
      auth: { username, password }
    });
```

This will use basic auth, but it no longer requires https://github.com/pouchdb-community/pouchdb-authentication

**Comment by greenais** [comment]
@zeevl , THANK you! 
My score: two days of pulling my hair
And the thing is that I couldn't find any traces of this way auth in current PDB docs after PDB changed it, nothing(

**Comment by zeevl** [comment]
Digging through the pouchdb source code. :(

**Comment by greenais** [comment]
What a shame to mantainers(
When auth is core functionality...

**Comment by mjafarpour** [comment]
> What a shame to mantainers(
> When auth is core functionality...

 I have same problem. run all recommended but get 401 error in replication and API calls.
Cookie set but not read in future API calls.
'auth' not worked in init time...
i am confused about what happen...

**Comment by steodor** [comment]
@mjafarpour the official fix is not rolled out yet, so you'll have to do it yourself for now. You have 2 options:

1. apply @zeevl's method above and use basic auth **ONLY IF** the security requirements of your project allow storing/sending passwords in plain-text;

2. for secure, production web apps i recommend applying @daleharvey's fix in your final code bundle, temporarily until the next release is rolled out. [In this pull request](https://github.com/pouchdb/pouchdb/pull/7395/files) is the code provided by `pouchdb-adapter-http`, and containing the fix. So inject the `options.credentials = 'include';` line just after the headers are being set. Do this in the final js bundle, after any other build process (namely bundling), and just before any minification. How you do that depends on your particular build process, a manual copy/paste would do the job just fine in the most simple case.

**Comment by jlami** [comment]
Because pouchdb-authentication is not working with fetch yet, I was testing some things myself. But I noticed that even when successfully POSTing a new session, the cookie response was not stored. This is due to a bug in fetch-cookie@0.7.0. Switching to 0.7.2 will fix this.

**Comment by TWry** [comment]
@jlami Could you elaborate on your fix, please? Is this a 3rd option to fix fix the issues with pouchdb-authentication?

@steodor I can't find `pouchdb-adapter-http` in node_modules - do I need to manually install it?

**Comment by jlami** [comment]
My problem might be more relevant to using pouchdb on a node server. The browser will handle any set-cookie for you and will send them back with future requests (if you set the options.credentials = 'include'). You can also fix the missing credentials by giving the pouchdb constructor a custom fetch where you set the option like this:

```js
      let db = new PouchDB(remote_couch, {
        fetch: function (url, opts) {
          opts.credentials = 'include';
          return PouchDB.fetch(url, opts);
        }
      });
```

This might be more user friendly than having to hack in node_modules files.


But when you are using pouchdb on node, it itself has to take care of the cookie store. This is done by using fetch-cookie, which sets the cookie headers for you. But due to a bug in 0.7.0 there this won't work if the initial request already has headers set, which pouchdb requests have. So if pouchdb could update to fetch-cookie@0.7.2 nodejs would be fixed. But I guess I might have been hijacking this topic. I will make a separate issue or PR for this.

**Comment by steodor** [comment]
@jlami i understand, but in client-side code that didn't work for us. That would have been a much better solution, nobody likes hacking 3rd-party plugin code in the way i suggested. It's ugly, i totally agree, but until the official fix is rolled out it was the only working fix we could come up with.

@TWry there is no mention of `node_modules` in any of my replies, i don't know why you would look there. I said "**Do this in the final js bundle**", which means your app's final code, not `pouchdb`'s or any other plugin's code.
So, open the js bundle file that your app's build process generates, and search for e.g. `if (opts.auth || host.auth) {` (or any other specific-enough line in [the pull request](https://github.com/pouchdb/pouchdb/pull/7395/files)). You should be able to find the code, patch it like the pull request does, and be on your way.

Hopefully though, the official fix will be rolled out soon and we can forget about doing this ugly stuff :)
