### ISSUE TITLE
opts.PouchConstructor is undefined

### ISSUE THREAD

**Issue by pixelcort** [pouchdb/pouchdb#2741]
After upgrading from 3.0.3 to 3.0.4, when I call `PouchDB.sync('localdbname', 'http://example.com/remotedbname')`, I get the error `TypeError: undefined is not a function`.

This is in the following code:

```
function toPouch(db, opts) {
  var PouchConstructor = opts.PouchConstructor;
  if (typeof db === 'string') {
    return new PouchConstructor(db);
```

In this case, `opts` is `{}`.
